---
- name: debian | Installing Pre-Req Packages
  apt:
    name: ['lldpd']
    state: present
  become: true
  register: result
  until: result is successful
  when: config_install_lldp | bool

- name: debian | Installing bridge-utils
  apt:
    name: ['bridge-utils']
    state: present
  become: true
  register: result
  until: result is successful
  when: config_network_bridges

- name: debian | Installing Bonding Packages
  apt:
    name: ['ifenslave']
    state: present
  become: true
  register: result
  until: result is successful
  when: config_network_bonds

# Don't install vlan package for proxmox-ve
- name: debian | Installing VLAN Packages
  apt:
    name: ['vlan']
    state: present
  become: true
  register: result
  until: result is successful
  when: 'config_network_vlans and "proxmox-ve" not in ansible_facts.packages'

- name: debian | Configuring Defined Interfaces
  template:
    src: '{{ config_interface_template }}'
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: true
  register: config_interface
  become: true
  when: >
    (config_network_interfaces is defined and
    config_network_interfaces)
  notify: enable networking

- name: debian | Restart networking.service
  service:
    name: networking
    state: restarted
  when: >
    enable_configured_interfaces_after_defining and
    config_interface['changed']
