---
# combine variables
- ansible.builtin.include_tasks:
    file: combine_vars.yml
    apply:
      tags: always
  tags: always

# tasks file for ansible-config-interfaces
- ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
