---
- name: redhat | Enabling EPEL repo
  ansible.builtin.yum:
    name: ["epel-release"]
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Pre-Reqs
  ansible.builtin.yum:
    name: ["lldpd"]
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - config_install_lldp | bool
    - ansible_distribution != "Fedora"

- name: redhat | Installing bridge-utils
  ansible.builtin.yum:
    name: ["bridge-utils"]
  become: true
  register: result
  until: result is successful
  when: >
    config_network_bridges and
    ansible_distribution != "Fedora"

- name: redhat | Installing VLAN Packages
  ansible.builtin.yum:
    name: ["vconfig"]
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    config_network_vlans and
    ansible_distribution != "Fedora"

- name: redhat | Enabling Bonding
  community.general.modprobe:
    name: bonding
    state: present
  become: true
  when: config_network_bonds

- name: redhat | Enabling Bridging
  community.general.modprobe:
    name: bridge
    state: present
  become: true
  when: config_network_bridges

- name: redhat | Configuring Interfaces
  ansible.builtin.template:
    src: etc/sysconfig/network-scripts/ifcfg.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.key }}"
  register: config_interface
  become: true
  loop: "{{ network_interfaces | dict2items }}"
  when:
    - config_network_interfaces and
    - item.value["configure"]

- name: redhat | Configuring Bonds
  ansible.builtin.template:
    src: etc/sysconfig/network-scripts/ifcfg.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.key }}"
  register: config_bond
  become: true
  loop: "{{ network_bonds | dict2items }}"
  when:
    - config_network_bonds
    - item.value["configure"]

- name: redhat | Configuring Bridges
  ansible.builtin.template:
    src: etc/sysconfig/network-scripts/ifcfg.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.key }}"
  register: config_bridge
  become: true
  loop: "{{ network_bridges | dict2items }}"
  when:
    - config_network_bridges and
    - item.value["configure"]

- name: redhat | Restarting Network Bonds
  ansible.builtin.shell: bash -c "ifdown {{ item['item']['name'] }} && ifup {{ item['item']['name'] }}"
  become: true
  loop: "{{ config_bond['results'] }}"
  when:
    - config_network_bonds
    - enable_configured_interfaces_after_defining
    - item["item"]["configure"]
    - item["changed"]

- name: redhat | Restarting Network Bridges
  ansible.builtin.shell: bash -c "ifdown {{ item['item']['name'] }} && ifup {{ item['item']['name'] }}"
  become: true
  loop: "{{ config_bridge['results'] }}"
  when:
    - config_network_bridges
    - enable_configured_interfaces_after_defining
    - item["item"]["configure"]
    - item["changed"]

- name: redhat | Restarting Network Interfaces
  ansible.builtin.shell: bash -c "ifdown {{ item['item']['name'] }} && ifup {{ item['item']['name'] }}"
  become: true
  loop: "{{ config_interface['results'] }}"
  when:
    - config_network_interfaces
    - enable_configured_interfaces_after_defining
    - item["item"]["configure"]
    - item["changed"]
